"""Type definitions and interfaces for the MAKER framework."""

from enum import Enum
from typing import Any, Dict, List, Literal, Optional, Protocol, TypedDict, Union
from typing_extensions import NotRequired


class Confidence(str, Enum):
    """Confidence level for the synthesized answer."""

    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"


class Message(TypedDict):
    """Message structure for LLM communication."""

    role: Literal["system", "user", "assistant"]
    content: str


class TokenUsage(TypedDict):
    """Token usage statistics."""

    prompt_tokens: int
    completion_tokens: int
    total_tokens: int


class CompletionRequest(TypedDict):
    """Request structure for LLM completion."""

    messages: List[Message]
    temperature: float
    max_tokens: NotRequired[int]
    response_format: NotRequired[Dict[str, Any]]


class CompletionResponse(TypedDict):
    """Response structure from LLM completion."""

    content: str
    raw: str
    usage: TokenUsage


class LLMProvider(Protocol):
    """Protocol defining the interface for LLM providers."""

    async def complete(self, request: CompletionRequest) -> CompletionResponse:
        """
        Generate a completion from the LLM.

        Args:
            request: The completion request with messages and parameters.

        Returns:
            The completion response with content and metadata.
        """
        ...


class SubQuestion(TypedDict):
    """A sub-question generated by decomposition."""

    question: str
    reasoning: str


class Classification(TypedDict):
    """Classification result for whether decomposition is needed."""

    needs_decomposition: bool
    reasoning: str
    complexity_score: int


class DecompositionResult(TypedDict):
    """Result of question decomposition."""

    sub_questions: List[SubQuestion]
    classification: Classification


class VoteCount(TypedDict):
    """Vote count for a specific answer."""

    answer: str
    count: int


class VotingResult(TypedDict):
    """Result of voting process for a sub-question."""

    answer: str
    consensus_reached: bool
    vote_counts: List[VoteCount]
    total_votes: int
    red_flagged_count: int


class SubQuestionResult(TypedDict):
    """Complete result for a sub-question including voting."""

    question: str
    answer: str
    consensus_reached: bool
    vote_counts: List[VoteCount]
    total_votes: int
    red_flagged_count: int


class VotingStats(TypedDict):
    """Aggregated voting statistics across all sub-questions."""

    total_votes: int
    total_red_flagged: int
    consensus_rate: float
    avg_votes_per_question: float


class MakerResult(TypedDict):
    """Final result from the MAKER framework."""

    answer: str
    confidence: Confidence
    consensus_reached: bool
    is_decomposed: bool
    sub_questions: NotRequired[List[SubQuestionResult]]
    voting_stats: VotingStats
    execution_time_ms: float


class VotingConfig(TypedDict, total=False):
    """Configuration for voting engine."""

    k: int  # Winner must be k votes ahead
    max_votes: int  # Safety limit for continuous voting


class RedFlagConfig(TypedDict, total=False):
    """Configuration for red-flag filter."""

    max_tokens: int  # Flag responses exceeding this token count
    min_chars: int  # Flag responses below this character count


class AzureConfig(TypedDict, total=False):
    """Configuration for Azure OpenAI."""

    endpoint: str
    api_version: str
    deployment: Optional[str]


class MakerConfig(TypedDict):
    """Configuration for the MAKER framework."""

    provider: Union[str, LLMProvider]
    api_key: str
    model: str
    voting: NotRequired[VotingConfig]
    red_flags: NotRequired[RedFlagConfig]
    azure: NotRequired[AzureConfig]


class AskOptions(TypedDict, total=False):
    """Options for asking a question."""

    context: str
    max_sub_questions: int


class RedFlagReason(str, Enum):
    """Reasons for red-flagging a response."""

    TOO_LONG = "too_long"
    TOO_SHORT = "too_short"
    PARSE_FAILURE = "parse_failure"
    NONE = "none"


class RedFlagResult(TypedDict):
    """Result of red-flag checking."""

    is_flagged: bool
    reason: RedFlagReason
