"""Type definitions and interfaces for the MAKER framework."""

from enum import Enum
from typing import Any, Dict, List, Literal, Optional, Protocol, TypedDict, Union
from typing_extensions import NotRequired


class Confidence(str, Enum):
    """Confidence level for the synthesized answer."""

    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"


class Message(TypedDict):
    """Message structure for LLM communication."""

    role: Literal["system", "user", "assistant"]
    content: str


class TokenUsage(TypedDict):
    """Token usage statistics."""

    prompt_tokens: int
    completion_tokens: int
    total_tokens: int


class CompletionRequest(TypedDict):
    """Request structure for LLM completion."""

    messages: List[Message]
    temperature: float
    max_tokens: NotRequired[int]
    response_format: NotRequired[Dict[str, Any]]


class CompletionResponse(TypedDict):
    """Response structure from LLM completion."""

    content: str
    raw: str
    usage: TokenUsage


class LLMProvider(Protocol):
    """Protocol defining the interface for LLM providers."""

    async def complete(self, request: CompletionRequest) -> CompletionResponse:
        """
        Generate a completion from the LLM.

        Args:
            request: The completion request with messages and parameters.

        Returns:
            The completion response with content and metadata.
        """
        ...


class SubQuestion(TypedDict):
    """A sub-question generated by decomposition."""

    question: str
    reasoning: str


class Classification(TypedDict):
    """Classification result for whether decomposition is needed."""

    needs_decomposition: bool
    reasoning: str
    complexity_score: int


class DecompositionResult(TypedDict):
    """Result of question decomposition."""

    sub_questions: List[SubQuestion]
    classification: Classification


class VotingResult(TypedDict):
    """Result of voting process for a sub-question.
    
    Per MAKER paper, tracks both total votes attempted and valid votes counted,
    as well as consensus status and vote statistics.
    """

    answer: str
    consensus_reached: bool
    vote_counts: Dict[str, int]  # normalized_answer -> count
    rounds_taken: int  # Total voting rounds attempted
    valid_votes: int  # Votes that weren't red-flagged
    red_flags_encountered: int  # Votes that were red-flagged and discarded
    winning_vote_count: int  # Number of votes for the winner
    margin: int  # Winner votes - runner-up votes


class SubQuestionResult(TypedDict):
    """Complete result for a sub-question including voting."""

    question: str
    answer: str
    consensus_reached: bool
    vote_counts: Dict[str, int]
    rounds_taken: int
    valid_votes: int
    red_flags_encountered: int
    confidence: NotRequired[str]  # "high", "medium", "low"


class VotingStats(TypedDict):
    """Aggregated voting statistics across all sub-questions."""

    total_votes: int
    valid_votes: int
    total_red_flagged: int
    winning_vote_count: int
    margin: int
    k: int  # The K value used for consensus


class MakerResult(TypedDict):
    """Final result from the MAKER framework."""

    answer: str
    confidence: Confidence
    consensus_reached: bool
    is_decomposed: bool
    sub_questions: NotRequired[List[SubQuestionResult]]
    synthesis_strategy: NotRequired[str]
    voting_stats: VotingStats
    total_tokens: NotRequired[int]
    execution_time_ms: float


class VotingConfig(TypedDict, total=False):
    """Configuration for voting engine."""

    k: int  # Winner must be k votes ahead
    max_votes: int  # Safety limit for continuous voting


class RedFlagConfig(TypedDict, total=False):
    """Configuration for red-flag filter."""

    max_tokens: int  # Flag responses exceeding this token count
    min_chars: int  # Flag responses below this character count


class DecompositionConfig(TypedDict, total=False):
    """Configuration for decomposition."""

    enabled: bool
    max_sub_questions: int


class SynthesisConfig(TypedDict, total=False):
    """Configuration for synthesis."""

    enabled: bool
    language: str


class AzureConfig(TypedDict, total=False):
    """Configuration for Azure OpenAI."""

    endpoint: str
    api_version: str
    deployment: Optional[str]


class MakerConfig(TypedDict, total=False):
    """Configuration for the MAKER framework.
    
    Can accept either:
    1. Provider string with API key (creates provider internally)
    2. LLMProvider instance (uses directly)
    """

    # Provider configuration
    provider: Union[str, "LLMProvider"]
    api_key: NotRequired[str]
    model: NotRequired[str]
    base_url: NotRequired[str]
    
    # Component configurations
    voting: NotRequired[VotingConfig]
    red_flags: NotRequired[RedFlagConfig]
    decomposition: NotRequired[DecompositionConfig]
    synthesis: NotRequired[SynthesisConfig]
    azure: NotRequired[AzureConfig]
    
    # Simple config options (backwards compatibility)
    voting_threshold: NotRequired[int]
    max_voting_rounds: NotRequired[int]
    max_sub_questions: NotRequired[int]
    enable_red_flag_filter: NotRequired[bool]


class AskOptions(TypedDict, total=False):
    """Options for asking a question."""

    context: str
    max_sub_questions: int
    k: int  # Override K value for this question


class RedFlagReason(str, Enum):
    """Reasons for red-flagging a response."""

    TOO_LONG = "too_long"
    TOO_SHORT = "too_short"
    PARSE_FAILURE = "parse_failure"
    NONE = "none"


class RedFlagResult(TypedDict):
    """Result of red-flag checking."""

    is_flagged: bool
    reason: RedFlagReason
